// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: config.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getConfig = `-- name: GetConfig :one
SELECT value FROM config
WHERE key = $1
  AND (org_id = $2 OR org_id IS NULL)
ORDER BY org_id NULLS LAST
LIMIT 1
`

type GetConfigParams struct {
	Key   string
	OrgID pgtype.Int8
}

// Resolve a config key for an org: an org-specific row wins, otherwise the
// global (NULL org_id) default. NULLS LAST orders the concrete org row ahead of
// the global fallback.
func (q *Queries) GetConfig(ctx context.Context, arg GetConfigParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getConfig, arg.Key, arg.OrgID)
	var value []byte
	err := row.Scan(&value)
	return value, err
}
