// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: episodes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceEpisodeStage = `-- name: AdvanceEpisodeStage :one
UPDATE episodes
SET proxy_object_key = COALESCE($1, proxy_object_key),
    duration_ms = COALESCE($2, duration_ms),
    error_id = NULL,
    claimed_at = now(),
    updated_at = now()
WHERE public_id = $3
  AND org_id = $4
  AND status = 'processing'
  AND current_stage = $5
  AND deleted_at IS NULL
RETURNING id, public_id, org_id, show_id, title, source_filename, language, status, duration_ms, master_object_key, proxy_object_key, error_id, created_at, updated_at, deleted_at, master_size_bytes, claimed_at, current_stage
`

type AdvanceEpisodeStageParams struct {
	ProxyObjectKey pgtype.Text
	DurationMs     pgtype.Int8
	PublicID       pgtype.UUID
	OrgID          int64
	CurrentStage   pgtype.Text
}

// Non-terminal (intermediate) stage finalize: the stage completed but a next
// stage will run, so the episode STAYS 'processing'. It records the stage's
// outputs (proxy key + measured duration; a NULL arg leaves the existing value
// untouched via COALESCE), clears error_id, and RE-ARMS claimed_at = now() so the
// stale-claim sweep grants the next stage a fresh TTL to start — the handoff
// window is never left with a NULL claimed_at, which the sweep would treat as a
// dead legacy claim and force-fail immediately. current_stage is left AT the
// completing stage on purpose: the next stage's claim advances it (that
// current_stage transition is the continuation claim's compare-and-set guard).
// Org-scoped and gated on 'processing' + current_stage = the completing stage, so
// a lost race, a foreign org, or a stage that no longer matches is an idempotent
// no-op (pgx.ErrNoRows) — never a cross-tenant or out-of-order write.
func (q *Queries) AdvanceEpisodeStage(ctx context.Context, arg AdvanceEpisodeStageParams) (Episode, error) {
	row := q.db.QueryRow(ctx, advanceEpisodeStage,
		arg.ProxyObjectKey,
		arg.DurationMs,
		arg.PublicID,
		arg.OrgID,
		arg.CurrentStage,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.ShowID,
		&i.Title,
		&i.SourceFilename,
		&i.Language,
		&i.Status,
		&i.DurationMs,
		&i.MasterObjectKey,
		&i.ProxyObjectKey,
		&i.ErrorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.MasterSizeBytes,
		&i.ClaimedAt,
		&i.CurrentStage,
	)
	return i, err
}

const claimEpisodeForStage = `-- name: ClaimEpisodeForStage :one
UPDATE episodes
SET status = 'processing',
    current_stage = $1,
    claimed_at = now(),
    error_id = NULL,
    updated_at = now()
WHERE public_id = $2
  AND deleted_at IS NULL
  AND (
        ($3::text IS NULL AND status = 'uploaded')
     OR ($3::text IS NOT NULL
         AND status = 'processing'
         AND current_stage = $3)
      )
RETURNING id, public_id, org_id, show_id, title, source_filename, language, status, duration_ms, master_object_key, proxy_object_key, error_id, created_at, updated_at, deleted_at, master_size_bytes, claimed_at, current_stage
`

type ClaimEpisodeForStageParams struct {
	Stage     pgtype.Text
	PublicID  pgtype.UUID
	PrevStage pgtype.Text
}

// Stage-aware compare-and-set claim: atomically take an episode for a stage,
// stamp current_stage = the stage, and re-arm claimed_at = now(). Two shapes,
// selected by prev_stage:
//
//   - Entry stage (prev_stage IS NULL, e.g. ingest): move a single 'uploaded'
//     episode to 'processing'. The status predicate is the concurrency guard — a
//     second concurrent worker finds no matching row and no-ops (pgx.ErrNoRows).
//     Behaviour is identical to the M0 ingest claim, plus setting current_stage.
//
//   - Continuation stage (prev_stage set): the episode is already 'processing',
//     sitting at the predecessor stage (the prior stage's finalize left
//     current_stage there). The guard current_stage = prev_stage is the
//     compare-and-set: the first claim advances current_stage to the new stage,
//     so a duplicate/concurrent claim finds no matching row and no-ops. This is
//     what makes auto-advance loop- and skip-proof: a stage can only be claimed
//     from its immediate predecessor, never from itself or an earlier stage.
//
// The returned org_id is how the worker scopes every later write to the claimed
// tenant; it never takes an org from its arguments. claimed_at is the backstop
// signal the stale-claim sweeper reads to force-fail a 'processing' row whose
// worker died without finalizing it.
func (q *Queries) ClaimEpisodeForStage(ctx context.Context, arg ClaimEpisodeForStageParams) (Episode, error) {
	row := q.db.QueryRow(ctx, claimEpisodeForStage, arg.Stage, arg.PublicID, arg.PrevStage)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.ShowID,
		&i.Title,
		&i.SourceFilename,
		&i.Language,
		&i.Status,
		&i.DurationMs,
		&i.MasterObjectKey,
		&i.ProxyObjectKey,
		&i.ErrorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.MasterSizeBytes,
		&i.ClaimedAt,
		&i.CurrentStage,
	)
	return i, err
}

const deleteOrphanEpisode = `-- name: DeleteOrphanEpisode :execrows
DELETE FROM episodes
WHERE public_id = $1
  AND org_id = $2
  AND status = 'uploaded'
  AND master_object_key IS NULL
`

type DeleteOrphanEpisodeParams struct {
	PublicID pgtype.UUID
	OrgID    int64
}

// Compensating rollback for a create that failed AFTER the row was inserted but
// BEFORE an upload URL could be minted (e.g. signing unavailable). It hard-deletes
// the just-created row so a failed create leaves nothing behind. It is narrowly
// gated — org-scoped, status still 'uploaded', and no master key yet — so it can
// only ever remove a fresh orphan, never an episode that started uploading or
// advanced. Returns the affected-row count so a caller can log a no-op.
func (q *Queries) DeleteOrphanEpisode(ctx context.Context, arg DeleteOrphanEpisodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOrphanEpisode, arg.PublicID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEpisodeByPublicID = `-- name: GetEpisodeByPublicID :one
SELECT id, public_id, org_id, show_id, title, source_filename, language, status, duration_ms, master_object_key, proxy_object_key, error_id, created_at, updated_at, deleted_at, master_size_bytes, claimed_at, current_stage FROM episodes
WHERE public_id = $1
  AND org_id = $2
  AND deleted_at IS NULL
`

type GetEpisodeByPublicIDParams struct {
	PublicID pgtype.UUID
	OrgID    int64
}

func (q *Queries) GetEpisodeByPublicID(ctx context.Context, arg GetEpisodeByPublicIDParams) (Episode, error) {
	row := q.db.QueryRow(ctx, getEpisodeByPublicID, arg.PublicID, arg.OrgID)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.ShowID,
		&i.Title,
		&i.SourceFilename,
		&i.Language,
		&i.Status,
		&i.DurationMs,
		&i.MasterObjectKey,
		&i.ProxyObjectKey,
		&i.ErrorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.MasterSizeBytes,
		&i.ClaimedAt,
		&i.CurrentStage,
	)
	return i, err
}

const getEpisodeStatusByPublicID = `-- name: GetEpisodeStatusByPublicID :one
SELECT status FROM episodes
WHERE public_id = $1
  AND deleted_at IS NULL
`

// Look up an episode's current status by public id alone (not org-scoped, like
// ClaimEpisodeForStage: the worker has no org until it claims). Used only to
// annotate the server-side WARN a worker logs when it cannot take a claim — the
// blocking status is why the claim was refused. Server-log-only, never client
// surface.
func (q *Queries) GetEpisodeStatusByPublicID(ctx context.Context, publicID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getEpisodeStatusByPublicID, publicID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const insertEpisode = `-- name: InsertEpisode :one
INSERT INTO episodes (
    org_id, show_id, title, source_filename, language, master_object_key, master_size_bytes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, public_id, org_id, show_id, title, source_filename, language, status, duration_ms, master_object_key, proxy_object_key, error_id, created_at, updated_at, deleted_at, master_size_bytes, claimed_at, current_stage
`

type InsertEpisodeParams struct {
	OrgID           int64
	ShowID          int64
	Title           string
	SourceFilename  string
	Language        string
	MasterObjectKey pgtype.Text
	MasterSizeBytes pgtype.Int8
}

func (q *Queries) InsertEpisode(ctx context.Context, arg InsertEpisodeParams) (Episode, error) {
	row := q.db.QueryRow(ctx, insertEpisode,
		arg.OrgID,
		arg.ShowID,
		arg.Title,
		arg.SourceFilename,
		arg.Language,
		arg.MasterObjectKey,
		arg.MasterSizeBytes,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.ShowID,
		&i.Title,
		&i.SourceFilename,
		&i.Language,
		&i.Status,
		&i.DurationMs,
		&i.MasterObjectKey,
		&i.ProxyObjectKey,
		&i.ErrorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.MasterSizeBytes,
		&i.ClaimedAt,
		&i.CurrentStage,
	)
	return i, err
}

const listEpisodesByOrg = `-- name: ListEpisodesByOrg :many
SELECT id, public_id, org_id, show_id, title, source_filename, language, status, duration_ms, master_object_key, proxy_object_key, error_id, created_at, updated_at, deleted_at, master_size_bytes, claimed_at, current_stage FROM episodes
WHERE org_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListEpisodesByOrg(ctx context.Context, orgID int64) ([]Episode, error) {
	rows, err := q.db.Query(ctx, listEpisodesByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Episode{}
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrgID,
			&i.ShowID,
			&i.Title,
			&i.SourceFilename,
			&i.Language,
			&i.Status,
			&i.DurationMs,
			&i.MasterObjectKey,
			&i.ProxyObjectKey,
			&i.ErrorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.MasterSizeBytes,
			&i.ClaimedAt,
			&i.CurrentStage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEpisodeFailed = `-- name: MarkEpisodeFailed :one
UPDATE episodes
SET status = 'failed',
    error_id = $3,
    claimed_at = NULL,
    updated_at = now()
WHERE public_id = $1
  AND org_id = $2
  AND status = 'processing'
  AND deleted_at IS NULL
RETURNING id, public_id, org_id, show_id, title, source_filename, language, status, duration_ms, master_object_key, proxy_object_key, error_id, created_at, updated_at, deleted_at, master_size_bytes, claimed_at, current_stage
`

type MarkEpisodeFailedParams struct {
	PublicID pgtype.UUID
	OrgID    int64
	ErrorID  pgtype.Text
}

// Finalize an exhausted stage: record a neutral error_id and flip to 'failed'.
// Org-scoped and gated on 'processing' for the same reason as MarkEpisodeReady.
// claimed_at is cleared: the run is done, no claim is in flight.
func (q *Queries) MarkEpisodeFailed(ctx context.Context, arg MarkEpisodeFailedParams) (Episode, error) {
	row := q.db.QueryRow(ctx, markEpisodeFailed, arg.PublicID, arg.OrgID, arg.ErrorID)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.ShowID,
		&i.Title,
		&i.SourceFilename,
		&i.Language,
		&i.Status,
		&i.DurationMs,
		&i.MasterObjectKey,
		&i.ProxyObjectKey,
		&i.ErrorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.MasterSizeBytes,
		&i.ClaimedAt,
		&i.CurrentStage,
	)
	return i, err
}

const markEpisodeReady = `-- name: MarkEpisodeReady :one
UPDATE episodes
SET status = 'ready',
    proxy_object_key = COALESCE($1, proxy_object_key),
    duration_ms = COALESCE($2, duration_ms),
    error_id = NULL,
    claimed_at = NULL,
    updated_at = now()
WHERE public_id = $3
  AND org_id = $4
  AND status = 'processing'
  AND deleted_at IS NULL
RETURNING id, public_id, org_id, show_id, title, source_filename, language, status, duration_ms, master_object_key, proxy_object_key, error_id, created_at, updated_at, deleted_at, master_size_bytes, claimed_at, current_stage
`

type MarkEpisodeReadyParams struct {
	ProxyObjectKey pgtype.Text
	DurationMs     pgtype.Int8
	PublicID       pgtype.UUID
	OrgID          int64
}

// Finalize a successful run: flip to 'ready', preserving the outputs earlier
// stages recorded. proxy_object_key/duration_ms are COALESCEd (a NULL arg leaves
// the existing value untouched), so the terminal stage — which today is
// transcribe, and produces no proxy or duration of its own — does not wipe the
// proxy key and measured duration ingest recorded. A stage that DOES produce them
// (a single-stage pipeline where ingest is terminal) still passes non-NULL and
// sets them, exactly as before. Org-scoped and gated on 'processing' so it only
// ever completes the run this worker claimed (idempotent no-op otherwise).
// claimed_at is cleared: the run is done, no claim is in flight.
func (q *Queries) MarkEpisodeReady(ctx context.Context, arg MarkEpisodeReadyParams) (Episode, error) {
	row := q.db.QueryRow(ctx, markEpisodeReady,
		arg.ProxyObjectKey,
		arg.DurationMs,
		arg.PublicID,
		arg.OrgID,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.ShowID,
		&i.Title,
		&i.SourceFilename,
		&i.Language,
		&i.Status,
		&i.DurationMs,
		&i.MasterObjectKey,
		&i.ProxyObjectKey,
		&i.ErrorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.MasterSizeBytes,
		&i.ClaimedAt,
		&i.CurrentStage,
	)
	return i, err
}

const retryFailedEpisode = `-- name: RetryFailedEpisode :one
UPDATE episodes
SET status = 'uploaded',
    error_id = NULL,
    claimed_at = NULL,
    updated_at = now()
WHERE public_id = $1
  AND org_id = $2
  AND status = 'failed'
  AND deleted_at IS NULL
RETURNING id, public_id, org_id, show_id, title, source_filename, language, status, duration_ms, master_object_key, proxy_object_key, error_id, created_at, updated_at, deleted_at, master_size_bytes, claimed_at, current_stage
`

type RetryFailedEpisodeParams struct {
	PublicID pgtype.UUID
	OrgID    int64
}

// State-guarded retry: atomically move a single 'failed' episode back to
// 'uploaded' so the ingest trigger can re-run it, clearing the prior error_id.
// Org-scoped and gated on status = 'failed', so a caller can only retry their
// own org's failed episode and a row in any other state is left untouched
// (pgx.ErrNoRows, which the handler maps to 409). claimed_at is cleared: the row
// returns to the unclaimed 'uploaded' state and the next claim stamps it fresh.
func (q *Queries) RetryFailedEpisode(ctx context.Context, arg RetryFailedEpisodeParams) (Episode, error) {
	row := q.db.QueryRow(ctx, retryFailedEpisode, arg.PublicID, arg.OrgID)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.ShowID,
		&i.Title,
		&i.SourceFilename,
		&i.Language,
		&i.Status,
		&i.DurationMs,
		&i.MasterObjectKey,
		&i.ProxyObjectKey,
		&i.ErrorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.MasterSizeBytes,
		&i.ClaimedAt,
		&i.CurrentStage,
	)
	return i, err
}

const setEpisodeMasterKey = `-- name: SetEpisodeMasterKey :one
UPDATE episodes
SET master_object_key = $3,
    updated_at = now()
WHERE public_id = $1
  AND org_id = $2
  AND deleted_at IS NULL
RETURNING id, public_id, org_id, show_id, title, source_filename, language, status, duration_ms, master_object_key, proxy_object_key, error_id, created_at, updated_at, deleted_at, master_size_bytes, claimed_at, current_stage
`

type SetEpisodeMasterKeyParams struct {
	PublicID        pgtype.UUID
	OrgID           int64
	MasterObjectKey pgtype.Text
}

// Record the verified master object key after the client confirms the upload
// landed. Org-scoped so a caller can only complete an upload for their own org's
// episode. Status is left as 'uploaded'; the worker flips it later.
func (q *Queries) SetEpisodeMasterKey(ctx context.Context, arg SetEpisodeMasterKeyParams) (Episode, error) {
	row := q.db.QueryRow(ctx, setEpisodeMasterKey, arg.PublicID, arg.OrgID, arg.MasterObjectKey)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.ShowID,
		&i.Title,
		&i.SourceFilename,
		&i.Language,
		&i.Status,
		&i.DurationMs,
		&i.MasterObjectKey,
		&i.ProxyObjectKey,
		&i.ErrorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.MasterSizeBytes,
		&i.ClaimedAt,
		&i.CurrentStage,
	)
	return i, err
}

const sweepAbandonedEpisodes = `-- name: SweepAbandonedEpisodes :execrows
DELETE FROM episodes
WHERE status = 'uploaded'
  AND master_object_key IS NULL
  AND created_at < now() - $1::interval
`

// System-level TTL sweep of abandoned uploads: a create can succeed
// server-side and then the CLIENT abandons the upload (CORS failure, closed tab,
// lost network), leaving a row stuck at 'uploaded' with no master key that no
// future PUT will ever complete. Across ALL orgs (this is a system maintenance
// sweep, not a tenant action, so it is deliberately not org-scoped) hard-delete
// rows older than the TTL whose upload never landed. The gate is the same narrow
// orphan shape as the create-time rollback (status 'uploaded', no master key)
// plus an age floor, so it can only ever remove a long-abandoned half-created
// row — never an episode that started uploading or advanced. Returns the count.
func (q *Queries) SweepAbandonedEpisodes(ctx context.Context, ttl pgtype.Interval) (int64, error) {
	result, err := q.db.Exec(ctx, sweepAbandonedEpisodes, ttl)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sweepStuckProcessingEpisodes = `-- name: SweepStuckProcessingEpisodes :execrows
UPDATE episodes
SET status = 'failed',
    error_id = $1,
    claimed_at = NULL,
    updated_at = now()
WHERE status = 'processing'
  AND (claimed_at IS NULL OR claimed_at < now() - $2::interval)
  AND deleted_at IS NULL
`

type SweepStuckProcessingEpisodesParams struct {
	ErrorID pgtype.Text
	Ttl     pgtype.Interval
}

// System-level stale-claim sweep: the backstop for a worker that entered
// 'processing' (Claim) but was SIGKILLed / OOM-killed / crashed before it could
// finalize the episode ready or failed. Cloud Run reports such an execution
// "succeeded" (the retry attempt sees 'processing' and cleanly no-ops), so the
// row would otherwise sit in 'processing' forever and the retry API — which only
// accepts 'failed' — could never rescue it. Across ALL orgs (system maintenance,
// deliberately not org-scoped) force-fail rows stuck in 'processing' whose claim
// is older than the TTL, OR whose claimed_at is NULL. A NULL claimed_at is a
// legacy claim taken before the claimed_at column existed (the currently-stuck
// prod episodes): treated as stale so the sweep unsticks them on the first pass.
// A neutral error_id is recorded (server-side correlation only, never client
// surface) and claimed_at cleared. Returns the count so the caller can WARN.
func (q *Queries) SweepStuckProcessingEpisodes(ctx context.Context, arg SweepStuckProcessingEpisodesParams) (int64, error) {
	result, err := q.db.Exec(ctx, sweepStuckProcessingEpisodes, arg.ErrorID, arg.Ttl)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateEpisodeStatus = `-- name: UpdateEpisodeStatus :one
UPDATE episodes
SET status = $3,
    updated_at = now()
WHERE public_id = $1
  AND org_id = $2
RETURNING id, public_id, org_id, show_id, title, source_filename, language, status, duration_ms, master_object_key, proxy_object_key, error_id, created_at, updated_at, deleted_at, master_size_bytes, claimed_at, current_stage
`

type UpdateEpisodeStatusParams struct {
	PublicID pgtype.UUID
	OrgID    int64
	Status   string
}

func (q *Queries) UpdateEpisodeStatus(ctx context.Context, arg UpdateEpisodeStatusParams) (Episode, error) {
	row := q.db.QueryRow(ctx, updateEpisodeStatus, arg.PublicID, arg.OrgID, arg.Status)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.ShowID,
		&i.Title,
		&i.SourceFilename,
		&i.Language,
		&i.Status,
		&i.DurationMs,
		&i.MasterObjectKey,
		&i.ProxyObjectKey,
		&i.ErrorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.MasterSizeBytes,
		&i.ClaimedAt,
		&i.CurrentStage,
	)
	return i, err
}
