// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: episodes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimEpisodeForIngest = `-- name: ClaimEpisodeForIngest :one
UPDATE episodes
SET status = 'processing',
    error_id = NULL,
    updated_at = now()
WHERE public_id = $1
  AND status = 'uploaded'
  AND deleted_at IS NULL
RETURNING id, public_id, org_id, show_id, title, source_filename, language, status, duration_ms, master_object_key, proxy_object_key, error_id, created_at, updated_at, deleted_at, master_size_bytes
`

// Compare-and-set claim: atomically move a single 'uploaded' episode to
// 'processing'. The status predicate is the concurrency guard — a second
// concurrent worker finds no matching row and no-ops (pgx.ErrNoRows). The
// returned org_id is how the worker scopes every later write to the claimed
// tenant; it never takes an org from its arguments.
func (q *Queries) ClaimEpisodeForIngest(ctx context.Context, publicID pgtype.UUID) (Episode, error) {
	row := q.db.QueryRow(ctx, claimEpisodeForIngest, publicID)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.ShowID,
		&i.Title,
		&i.SourceFilename,
		&i.Language,
		&i.Status,
		&i.DurationMs,
		&i.MasterObjectKey,
		&i.ProxyObjectKey,
		&i.ErrorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.MasterSizeBytes,
	)
	return i, err
}

const getEpisodeByPublicID = `-- name: GetEpisodeByPublicID :one
SELECT id, public_id, org_id, show_id, title, source_filename, language, status, duration_ms, master_object_key, proxy_object_key, error_id, created_at, updated_at, deleted_at, master_size_bytes FROM episodes
WHERE public_id = $1
  AND org_id = $2
  AND deleted_at IS NULL
`

type GetEpisodeByPublicIDParams struct {
	PublicID pgtype.UUID
	OrgID    int64
}

func (q *Queries) GetEpisodeByPublicID(ctx context.Context, arg GetEpisodeByPublicIDParams) (Episode, error) {
	row := q.db.QueryRow(ctx, getEpisodeByPublicID, arg.PublicID, arg.OrgID)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.ShowID,
		&i.Title,
		&i.SourceFilename,
		&i.Language,
		&i.Status,
		&i.DurationMs,
		&i.MasterObjectKey,
		&i.ProxyObjectKey,
		&i.ErrorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.MasterSizeBytes,
	)
	return i, err
}

const insertEpisode = `-- name: InsertEpisode :one
INSERT INTO episodes (
    org_id, show_id, title, source_filename, language, master_object_key, master_size_bytes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, public_id, org_id, show_id, title, source_filename, language, status, duration_ms, master_object_key, proxy_object_key, error_id, created_at, updated_at, deleted_at, master_size_bytes
`

type InsertEpisodeParams struct {
	OrgID           int64
	ShowID          int64
	Title           string
	SourceFilename  string
	Language        string
	MasterObjectKey pgtype.Text
	MasterSizeBytes pgtype.Int8
}

func (q *Queries) InsertEpisode(ctx context.Context, arg InsertEpisodeParams) (Episode, error) {
	row := q.db.QueryRow(ctx, insertEpisode,
		arg.OrgID,
		arg.ShowID,
		arg.Title,
		arg.SourceFilename,
		arg.Language,
		arg.MasterObjectKey,
		arg.MasterSizeBytes,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.ShowID,
		&i.Title,
		&i.SourceFilename,
		&i.Language,
		&i.Status,
		&i.DurationMs,
		&i.MasterObjectKey,
		&i.ProxyObjectKey,
		&i.ErrorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.MasterSizeBytes,
	)
	return i, err
}

const listEpisodesByOrg = `-- name: ListEpisodesByOrg :many
SELECT id, public_id, org_id, show_id, title, source_filename, language, status, duration_ms, master_object_key, proxy_object_key, error_id, created_at, updated_at, deleted_at, master_size_bytes FROM episodes
WHERE org_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListEpisodesByOrg(ctx context.Context, orgID int64) ([]Episode, error) {
	rows, err := q.db.Query(ctx, listEpisodesByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Episode{}
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrgID,
			&i.ShowID,
			&i.Title,
			&i.SourceFilename,
			&i.Language,
			&i.Status,
			&i.DurationMs,
			&i.MasterObjectKey,
			&i.ProxyObjectKey,
			&i.ErrorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.MasterSizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEpisodeFailed = `-- name: MarkEpisodeFailed :one
UPDATE episodes
SET status = 'failed',
    error_id = $3,
    updated_at = now()
WHERE public_id = $1
  AND org_id = $2
  AND status = 'processing'
  AND deleted_at IS NULL
RETURNING id, public_id, org_id, show_id, title, source_filename, language, status, duration_ms, master_object_key, proxy_object_key, error_id, created_at, updated_at, deleted_at, master_size_bytes
`

type MarkEpisodeFailedParams struct {
	PublicID pgtype.UUID
	OrgID    int64
	ErrorID  pgtype.Text
}

// Finalize an exhausted stage: record a neutral error_id and flip to 'failed'.
// Org-scoped and gated on 'processing' for the same reason as MarkEpisodeReady.
func (q *Queries) MarkEpisodeFailed(ctx context.Context, arg MarkEpisodeFailedParams) (Episode, error) {
	row := q.db.QueryRow(ctx, markEpisodeFailed, arg.PublicID, arg.OrgID, arg.ErrorID)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.ShowID,
		&i.Title,
		&i.SourceFilename,
		&i.Language,
		&i.Status,
		&i.DurationMs,
		&i.MasterObjectKey,
		&i.ProxyObjectKey,
		&i.ErrorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.MasterSizeBytes,
	)
	return i, err
}

const markEpisodeReady = `-- name: MarkEpisodeReady :one
UPDATE episodes
SET status = 'ready',
    proxy_object_key = $3,
    duration_ms = $4,
    error_id = NULL,
    updated_at = now()
WHERE public_id = $1
  AND org_id = $2
  AND status = 'processing'
  AND deleted_at IS NULL
RETURNING id, public_id, org_id, show_id, title, source_filename, language, status, duration_ms, master_object_key, proxy_object_key, error_id, created_at, updated_at, deleted_at, master_size_bytes
`

type MarkEpisodeReadyParams struct {
	PublicID       pgtype.UUID
	OrgID          int64
	ProxyObjectKey pgtype.Text
	DurationMs     pgtype.Int8
}

// Finalize a successful stage: record the proxy key and measured duration and
// flip to 'ready'. Org-scoped and gated on 'processing' so it only ever
// completes the run this worker claimed (idempotent no-op otherwise).
func (q *Queries) MarkEpisodeReady(ctx context.Context, arg MarkEpisodeReadyParams) (Episode, error) {
	row := q.db.QueryRow(ctx, markEpisodeReady,
		arg.PublicID,
		arg.OrgID,
		arg.ProxyObjectKey,
		arg.DurationMs,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.ShowID,
		&i.Title,
		&i.SourceFilename,
		&i.Language,
		&i.Status,
		&i.DurationMs,
		&i.MasterObjectKey,
		&i.ProxyObjectKey,
		&i.ErrorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.MasterSizeBytes,
	)
	return i, err
}

const setEpisodeMasterKey = `-- name: SetEpisodeMasterKey :one
UPDATE episodes
SET master_object_key = $3,
    updated_at = now()
WHERE public_id = $1
  AND org_id = $2
  AND deleted_at IS NULL
RETURNING id, public_id, org_id, show_id, title, source_filename, language, status, duration_ms, master_object_key, proxy_object_key, error_id, created_at, updated_at, deleted_at, master_size_bytes
`

type SetEpisodeMasterKeyParams struct {
	PublicID        pgtype.UUID
	OrgID           int64
	MasterObjectKey pgtype.Text
}

// Record the verified master object key after the client confirms the upload
// landed. Org-scoped so a caller can only complete an upload for their own org's
// episode. Status is left as 'uploaded'; the worker flips it later.
func (q *Queries) SetEpisodeMasterKey(ctx context.Context, arg SetEpisodeMasterKeyParams) (Episode, error) {
	row := q.db.QueryRow(ctx, setEpisodeMasterKey, arg.PublicID, arg.OrgID, arg.MasterObjectKey)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.ShowID,
		&i.Title,
		&i.SourceFilename,
		&i.Language,
		&i.Status,
		&i.DurationMs,
		&i.MasterObjectKey,
		&i.ProxyObjectKey,
		&i.ErrorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.MasterSizeBytes,
	)
	return i, err
}

const updateEpisodeStatus = `-- name: UpdateEpisodeStatus :one
UPDATE episodes
SET status = $3,
    updated_at = now()
WHERE public_id = $1
  AND org_id = $2
RETURNING id, public_id, org_id, show_id, title, source_filename, language, status, duration_ms, master_object_key, proxy_object_key, error_id, created_at, updated_at, deleted_at, master_size_bytes
`

type UpdateEpisodeStatusParams struct {
	PublicID pgtype.UUID
	OrgID    int64
	Status   string
}

func (q *Queries) UpdateEpisodeStatus(ctx context.Context, arg UpdateEpisodeStatusParams) (Episode, error) {
	row := q.db.QueryRow(ctx, updateEpisodeStatus, arg.PublicID, arg.OrgID, arg.Status)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.ShowID,
		&i.Title,
		&i.SourceFilename,
		&i.Language,
		&i.Status,
		&i.DurationMs,
		&i.MasterObjectKey,
		&i.ProxyObjectKey,
		&i.ErrorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.MasterSizeBytes,
	)
	return i, err
}
