// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: llm_calls.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertLlmCall = `-- name: InsertLlmCall :one
INSERT INTO llm_calls (
    org_id, episode_id, model, prompt_version, input_hash,
    raw_response, cost_cents, latency_ms, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, org_id, episode_id, model, prompt_version, input_hash, raw_response, cost_cents, latency_ms, created_at, updated_at, status
`

type InsertLlmCallParams struct {
	OrgID         int64
	EpisodeID     pgtype.Int8
	Model         string
	PromptVersion string
	InputHash     string
	RawResponse   []byte
	CostCents     pgtype.Int4
	LatencyMs     pgtype.Int4
	Status        pgtype.Text
}

// Append-only audit of a single model call made through /internal/llm. There is
// one row per provider call: successes, schema-invalid outputs, and failed or
// retried attempts alike (the one-retry semantics live in /internal/llm; here
// every attempt is recorded verbatim). org_id scopes the row to a tenant;
// episode_id is nullable for calls not tied to one episode. raw_response holds
// the provider response body verbatim (NULL when the upstream returned no valid
// JSON body). cost_cents is NULL when no price is configured for the model;
// latency_ms and status record the attempt's outcome.
func (q *Queries) InsertLlmCall(ctx context.Context, arg InsertLlmCallParams) (LlmCall, error) {
	row := q.db.QueryRow(ctx, insertLlmCall,
		arg.OrgID,
		arg.EpisodeID,
		arg.Model,
		arg.PromptVersion,
		arg.InputHash,
		arg.RawResponse,
		arg.CostCents,
		arg.LatencyMs,
		arg.Status,
	)
	var i LlmCall
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.EpisodeID,
		&i.Model,
		&i.PromptVersion,
		&i.InputHash,
		&i.RawResponse,
		&i.CostCents,
		&i.LatencyMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}
