// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memberships.sql

package db

import (
	"context"
)

const getMembershipRole = `-- name: GetMembershipRole :one
SELECT role FROM memberships
WHERE org_id = $1
  AND user_id = $2
`

type GetMembershipRoleParams struct {
	OrgID  int64
	UserID int64
}

func (q *Queries) GetMembershipRole(ctx context.Context, arg GetMembershipRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getMembershipRole, arg.OrgID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}
