// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Config struct {
	ID        int64
	OrgID     pgtype.Int8
	Key       string
	Value     []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type CorrectionLog struct {
	ID          int64
	OrgID       int64
	EpisodeID   int64
	SegmentIdx  int32
	Before      []byte
	After       []byte
	CorrectedBy int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Episode struct {
	ID              int64
	PublicID        pgtype.UUID
	OrgID           int64
	ShowID          int64
	Title           string
	SourceFilename  string
	Language        string
	Status          string
	DurationMs      pgtype.Int8
	MasterObjectKey pgtype.Text
	ProxyObjectKey  pgtype.Text
	ErrorID         pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	MasterSizeBytes pgtype.Int8
	ClaimedAt       pgtype.Timestamptz
	CurrentStage    pgtype.Text
	ProcessAttempts int32
}

type LlmCall struct {
	ID            int64
	OrgID         int64
	EpisodeID     pgtype.Int8
	Model         string
	PromptVersion string
	InputHash     string
	RawResponse   []byte
	CostCents     pgtype.Int4
	LatencyMs     pgtype.Int4
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Status        pgtype.Text
}

type Membership struct {
	ID        int64
	OrgID     int64
	UserID    int64
	Role      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Org struct {
	ID        int64
	PublicID  pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Segment struct {
	ID         int64
	EpisodeID  int64
	Idx        int32
	StartMs    int32
	EndMs      int32
	Text       string
	Words      []byte
	CreatedAt  pgtype.Timestamptz
	SpeakerKey pgtype.Text
}

type Show struct {
	ID        int64
	PublicID  pgtype.UUID
	OrgID     int64
	Title     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type User struct {
	ID          int64
	Email       string
	DisplayName string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}
