// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: moments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEpisodeMoments = `-- name: CountEpisodeMoments :one
SELECT count(*) FROM moments WHERE episode_id = $1
`

// Cost-safety idempotency probe for the moments stage: how many moments the
// episode already has. A non-zero count means the moment proposal already
// exists, so the stage SKIPS the billable LLM call entirely (never re-bills on a
// retry/re-drive). episode_id is the internal id, resolved org-scoped by the
// caller.
func (q *Queries) CountEpisodeMoments(ctx context.Context, episodeID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countEpisodeMoments, episodeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteEpisodeMoments = `-- name: DeleteEpisodeMoments :exec
DELETE FROM moments WHERE episode_id = $1
`

// Remove all of an episode's moments. Paired with InsertMoment inside one
// transaction, this makes a re-run of the moments stage idempotent: the prior
// proposal set is replaced wholesale rather than duplicated (mirroring the
// segments replace choreography). episode_id is the internal id, resolved
// org-scoped by the caller.
func (q *Queries) DeleteEpisodeMoments(ctx context.Context, episodeID int64) error {
	_, err := q.db.Exec(ctx, deleteEpisodeMoments, episodeID)
	return err
}

const insertMoment = `-- name: InsertMoment :exec
INSERT INTO moments (episode_id, rank, start_idx, end_idx, start_ms, end_ms, rationale_en, quote_fa)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertMomentParams struct {
	EpisodeID   int64
	Rank        int32
	StartIdx    int32
	EndIdx      int32
	StartMs     int32
	EndMs       int32
	RationaleEn string
	QuoteFa     string
}

// Insert one proposed moment. rationale_en/quote_fa are stored verbatim as the
// validated engine returned them (the quote is a contiguous substring of the
// span's transcript text — enforced before persist); start_ms/end_ms are the
// stage-derived WORD-ACCURATE times of the quote's first/last word within the
// span (ASR word data, never model output, never segment-snapped). status
// defaults to 'proposed'; only a human status update ever changes it.
func (q *Queries) InsertMoment(ctx context.Context, arg InsertMomentParams) error {
	_, err := q.db.Exec(ctx, insertMoment,
		arg.EpisodeID,
		arg.Rank,
		arg.StartIdx,
		arg.EndIdx,
		arg.StartMs,
		arg.EndMs,
		arg.RationaleEn,
		arg.QuoteFa,
	)
	return err
}

const listMomentsByEpisode = `-- name: ListMomentsByEpisode :many
SELECT rank, start_idx, end_idx, start_ms, end_ms, rationale_en, quote_fa, status, status_changed_at
FROM moments
WHERE episode_id = $1
ORDER BY rank
`

type ListMomentsByEpisodeRow struct {
	Rank            int32
	StartIdx        int32
	EndIdx          int32
	StartMs         int32
	EndMs           int32
	RationaleEn     string
	QuoteFa         string
	Status          string
	StatusChangedAt pgtype.Timestamptz
}

// List an episode's moments best-first (rank 1 = best). episode_id is the
// internal id, resolved org-scoped by the caller.
func (q *Queries) ListMomentsByEpisode(ctx context.Context, episodeID int64) ([]ListMomentsByEpisodeRow, error) {
	rows, err := q.db.Query(ctx, listMomentsByEpisode, episodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMomentsByEpisodeRow{}
	for rows.Next() {
		var i ListMomentsByEpisodeRow
		if err := rows.Scan(
			&i.Rank,
			&i.StartIdx,
			&i.EndIdx,
			&i.StartMs,
			&i.EndMs,
			&i.RationaleEn,
			&i.QuoteFa,
			&i.Status,
			&i.StatusChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionMomentStatus = `-- name: TransitionMomentStatus :one
UPDATE moments
SET status = $1, status_changed_at = now()
WHERE episode_id = $2
  AND rank = $3
  AND (
        (status = 'proposed' AND $1::text IN ('approved', 'dismissed'))
     OR (status IN ('approved', 'dismissed') AND $1::text = 'proposed')
  )
RETURNING id, status
`

type TransitionMomentStatusParams struct {
	Status    string
	EpisodeID int64
	Rank      int32
}

type TransitionMomentStatusRow struct {
	ID     int64
	Status string
}

// Flip one moment's review status, guarded to the legal transitions only:
// proposed -> approved/dismissed (the review verdicts) and approved/dismissed ->
// proposed (the undo). Any other combination matches no row, so the caller sees
// pgx.ErrNoRows and refuses cleanly. status_changed_at stamps the change.
// episode_id is the internal id, resolved org-scoped by the caller; (episode_id,
// rank) is the moment's stable natural key (UNIQUE in the schema).
func (q *Queries) TransitionMomentStatus(ctx context.Context, arg TransitionMomentStatusParams) (TransitionMomentStatusRow, error) {
	row := q.db.QueryRow(ctx, transitionMomentStatus, arg.Status, arg.EpisodeID, arg.Rank)
	var i TransitionMomentStatusRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}
