// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orgs.sql

package db

import (
	"context"
)

const getOrg = `-- name: GetOrg :one
SELECT id, public_id, name, created_at, updated_at FROM orgs
WHERE id = $1
`

func (q *Queries) GetOrg(ctx context.Context, id int64) (Org, error) {
	row := q.db.QueryRow(ctx, getOrg, id)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
