// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Non-terminal (intermediate) stage finalize: the stage completed but a next
	// stage will run, so the episode STAYS 'processing'. It records the stage's
	// outputs (proxy key + measured duration; a NULL arg leaves the existing value
	// untouched via COALESCE), clears error_id, and RE-ARMS claimed_at = now() so the
	// stale-claim sweep grants the next stage a fresh TTL to start — the handoff
	// window is never left with a NULL claimed_at, which the sweep would treat as a
	// dead legacy claim and force-fail immediately. current_stage is left AT the
	// completing stage on purpose: the next stage's claim advances it (that
	// current_stage transition is the continuation claim's compare-and-set guard).
	// Org-scoped and gated on 'processing' + current_stage = the completing stage, so
	// a lost race, a foreign org, or a stage that no longer matches is an idempotent
	// no-op (pgx.ErrNoRows) — never a cross-tenant or out-of-order write.
	AdvanceEpisodeStage(ctx context.Context, arg AdvanceEpisodeStageParams) (Episode, error)
	// Stage-aware compare-and-set claim: atomically take an episode for a stage,
	// stamp current_stage = the stage, and re-arm claimed_at = now(). Two shapes,
	// selected by prev_stage:
	//
	//   * Entry stage (prev_stage IS NULL, e.g. ingest): move a single 'uploaded'
	//     episode to 'processing'. The status predicate is the concurrency guard — a
	//     second concurrent worker finds no matching row and no-ops (pgx.ErrNoRows).
	//     Behaviour is identical to the M0 ingest claim, plus setting current_stage.
	//
	//   * Continuation stage (prev_stage set): the episode is already 'processing',
	//     sitting at the predecessor stage (the prior stage's finalize left
	//     current_stage there). The guard current_stage = prev_stage is the
	//     compare-and-set: the first claim advances current_stage to the new stage,
	//     so a duplicate/concurrent claim finds no matching row and no-ops. This is
	//     what makes auto-advance loop- and skip-proof: a stage can only be claimed
	//     from its immediate predecessor, never from itself or an earlier stage.
	//
	// The returned org_id is how the worker scopes every later write to the claimed
	// tenant; it never takes an org from its arguments. claimed_at is the backstop
	// signal the stale-claim sweeper reads to force-fail a 'processing' row whose
	// worker died without finalizing it.
	ClaimEpisodeForStage(ctx context.Context, arg ClaimEpisodeForStageParams) (Episode, error)
	// Cost-safety idempotency probe for the moments stage: how many PIPELINE
	// (source='auto') moments the episode already has. A non-zero count means the
	// stage's proposal set already exists, so the stage SKIPS the billable LLM
	// call entirely (never re-bills on a retry/re-drive). Scoped to 'auto'
	// deliberately: a kept user-composed moment is NOT the stage's output and
	// must never suppress the stage's own proposal run. episode_id is the
	// internal id, resolved org-scoped by the caller.
	CountAutoMoments(ctx context.Context, episodeID int64) (int64, error)
	// Cost-safety idempotency probe for the transcribe stage: how many transcript
	// segments the episode already has. A non-zero count means the episode is already
	// transcribed, so the stage SKIPS the billable ASR call entirely (never re-bills on
	// a retry/re-drive). episode_id is the internal id, resolved org-scoped by the
	// caller.
	CountEpisodeSegments(ctx context.Context, episodeID int64) (int64, error)
	// Cost-safety idempotency probe for the diarize stage: the episode's total segment
	// count and how many already carry a speaker_key (count() ignores NULLs, so
	// `diarized` counts only assigned rows). The stage treats "already diarized" as
	// total > 0 AND diarized = total, and then SKIPS the billable LLM call (never
	// re-bills on a retry/re-drive). episode_id is the internal id, resolved org-scoped
	// by the caller.
	CountEpisodeSegmentsAndSpeakers(ctx context.Context, episodeID int64) (CountEpisodeSegmentsAndSpeakersRow, error)
	// Remove all of an episode's PIPELINE-PROPOSED moments (source='auto').
	// Paired with InsertMoment inside one transaction, this makes a re-run of the
	// moments stage idempotent: the prior proposal set is replaced wholesale
	// rather than duplicated (mirroring the segments replace choreography).
	// Kept user-composed moments (source='prompt') deliberately survive the
	// replace — a reprocess never discards a human's kept composition. episode_id
	// is the internal id, resolved org-scoped by the caller.
	DeleteAutoMoments(ctx context.Context, episodeID int64) error
	// Remove all of an episode's segments. Paired with InsertSegment inside one
	// transaction, this makes a re-run of the transcribe stage idempotent: the prior
	// transcript is replaced wholesale rather than duplicated. episode_id is the
	// internal id, resolved org-scoped by the caller.
	DeleteEpisodeSegments(ctx context.Context, episodeID int64) error
	// Compensating rollback for a create that failed AFTER the row was inserted but
	// BEFORE an upload URL could be minted (e.g. signing unavailable). It hard-deletes
	// the just-created row so a failed create leaves nothing behind. It is narrowly
	// gated — org-scoped, status still 'uploaded', and no master key yet — so it can
	// only ever remove a fresh orphan, never an episode that started uploading or
	// advanced. Returns the affected-row count so a caller can log a no-op.
	// deleted_at IS NULL: a soft-deleted row is a frozen record of a tenant action
	// and no hard-delete path may touch it.
	DeleteOrphanEpisode(ctx context.Context, arg DeleteOrphanEpisodeParams) (int64, error)
	// Close a stage-run row at finalize time: stamp finished_at, the outcome, and
	// whatever the run learned (unit counts, billable attempt, tunables). Gated on
	// finished_at IS NULL so a double finalize (e.g. a lost race) is an idempotent
	// no-op that never rewrites a closed run.
	//
	// cost_cents: an explicitly computed cost (the ASR duration-rate) wins; when
	// none is passed, an LLM-backed stage (diarize/moments) links the cost from the
	// llm_calls audit — the sum of the episode's call costs recorded since this
	// run started. SUM over no rows is NULL, so a run with no audited cost stays
	// honestly unknown rather than zero.
	FinishStageRun(ctx context.Context, arg FinishStageRunParams) (int64, error)
	// Resolve a seeded user's authentication context by email: their display name,
	// their org (public id + name) and their role in that org. One membership per
	// user in M0, so LIMIT 1 is exact. Soft-deleted users are excluded.
	GetAuthContextByEmail(ctx context.Context, email string) (GetAuthContextByEmailRow, error)
	// Resolve a config key for an org: an org-specific row wins, otherwise the
	// global (NULL org_id) default. NULLS LAST orders the concrete org row ahead of
	// the global fallback.
	GetConfig(ctx context.Context, arg GetConfigParams) ([]byte, error)
	// The org's canonical show. Setup auto-creates exactly one show per org in M0,
	// so the lowest-id non-deleted show is that show. Every episode hangs off it
	// until per-show organization arrives.
	GetDefaultShowForOrg(ctx context.Context, orgID int64) (Show, error)
	GetEpisodeByPublicID(ctx context.Context, arg GetEpisodeByPublicIDParams) (Episode, error)
	// Look up an episode's current status by public id alone (not org-scoped, like
	// ClaimEpisodeForStage: the worker has no org until it claims). Used only to
	// annotate the server-side WARN a worker logs when it cannot take a claim — the
	// blocking status is why the claim was refused. Server-log-only, never client
	// surface.
	GetEpisodeStatusByPublicID(ctx context.Context, publicID pgtype.UUID) (string, error)
	GetMembershipRole(ctx context.Context, arg GetMembershipRoleParams) (string, error)
	GetOrg(ctx context.Context, id int64) (Org, error)
	// Resolve an org's internal row from the public id carried in the session
	// principal. This is how every org-scoped write turns the caller's org identity
	// (never client input) into the internal org_id used by the queries below.
	GetOrgByPublicID(ctx context.Context, publicID pgtype.UUID) (Org, error)
	// Cost-safety gate (CLAUDE.md "Billable-service cost safety"): atomically record
	// that a billable stage is about to start a paid engine call, but ONLY while the
	// per-episode attempt count is still below the cap. It increments process_attempts
	// and returns the new value; the CHECK `process_attempts < max_attempts` in the
	// WHERE clause makes it a compare-and-set — at or above the cap NO row matches, so
	// nothing is incremented and the caller gets pgx.ErrNoRows, which the store maps to
	// "not allowed" so the stage refuses to call the engine. Org-scoped like the other
	// finalizers (the stage supplies the org it claimed), so it can never bump another
	// tenant's counter. This is the ONLY writer of process_attempts.
	IncrementEpisodeProcessAttemptsBelowCap(ctx context.Context, arg IncrementEpisodeProcessAttemptsBelowCapParams) (int32, error)
	InsertEpisode(ctx context.Context, arg InsertEpisodeParams) (Episode, error)
	// Append-only audit of a single model call made through /internal/llm. There is
	// one row per provider call: successes, schema-invalid outputs, and failed or
	// retried attempts alike (the one-retry semantics live in /internal/llm; here
	// every attempt is recorded verbatim). org_id scopes the row to a tenant;
	// episode_id is nullable for calls not tied to one episode. raw_response holds
	// the provider response body verbatim (NULL when the upstream returned no valid
	// JSON body). cost_cents is NULL when no price is configured for the model;
	// latency_ms and status record the attempt's outcome.
	InsertLlmCall(ctx context.Context, arg InsertLlmCallParams) (LlmCall, error)
	// Insert one stage-proposed moment (source defaults to 'auto'). rationale_en/
	// quote_fa are stored verbatim as the validated engine returned them (the
	// quote is a contiguous substring of the span's transcript text — enforced
	// before persist); start_ms/end_ms are the stage-derived WORD-ACCURATE times
	// of the quote's first/last word within the span (ASR word data, never model
	// output, never segment-snapped). status defaults to 'proposed'; only a human
	// status update ever changes it.
	InsertMoment(ctx context.Context, arg InsertMomentParams) error
	// Persist one KEPT user-composed moment (approve-to-keep) at the episode's
	// next free rank — rank = max(rank)+1 computed atomically in the same
	// statement, so UNIQUE(episode_id, rank) holds without the caller reading
	// first (a concurrent keep loses the race as a unique violation the caller
	// retries). The row lands source='prompt' and status='approved' with
	// status_changed_at stamped: keeping IS the human's approval verdict. Texts
	// and times carry the same verbatim/word-accurate contract as InsertMoment —
	// the caller re-validated the quote and re-derived the times against the
	// CURRENT transcript before persisting. episode_id is the internal id,
	// resolved org-scoped by the caller.
	InsertPromptMoment(ctx context.Context, arg InsertPromptMomentParams) (InsertPromptMomentRow, error)
	// Insert one transcript segment. `words` is the positional jsonb array the schema
	// documents ([text, start_ms, end_ms, conf] tuples); text/words are stored
	// verbatim from ASR (no normalization at rest). speaker_key starts NULL (not yet
	// diarized); the diarize stage sets it later via SetSegmentSpeaker.
	InsertSegment(ctx context.Context, arg InsertSegmentParams) error
	// Open a stage-run provenance row at claim time: append-only history, so a
	// re-run/retry INSERTS a new row (never updates the old one) and display reads
	// take the latest row per stage. started_at is the DB clock (DEFAULT now()) —
	// the wall-clock record; duration is derived at read time, never stored.
	// engine_detail is the PRIVATE provider truth and never leaves the server;
	// engine_label is the PUBLIC versioned neutral label.
	InsertStageRun(ctx context.Context, arg InsertStageRunParams) (int64, error)
	// The display read: the LATEST run per stage for one episode (history rows on
	// re-runs; latest-per-stage wins). engine_detail is deliberately selected too —
	// this query serves the SERVER-side port; the api layer's port type has no
	// field for it, so it can never reach a DTO.
	LatestStageRuns(ctx context.Context, episodeID int64) ([]StageRun, error)
	ListEpisodesByOrg(ctx context.Context, orgID int64) ([]Episode, error)
	// List an episode's moments best-first (rank 1 = best; kept composed moments
	// rank after the auto set by construction). episode_id is the internal id,
	// resolved org-scoped by the caller.
	ListMomentsByEpisode(ctx context.Context, episodeID int64) ([]ListMomentsByEpisodeRow, error)
	// The episode's kept composed moments (source='prompt') in rank order — the
	// rows the stage replace must renumber to follow a fresh auto set (see
	// ReplaceMoments: the new auto ranks are 1..n, composed rows continue n+1..).
	// episode_id is the internal id, resolved org-scoped by the caller.
	ListPromptMomentIDs(ctx context.Context, episodeID int64) ([]int64, error)
	// List an episode's transcript in order, including the diarization speaker_key
	// (NULL until the diarize stage runs). episode_id is the internal id, resolved
	// org-scoped by the caller.
	ListSegmentsByEpisode(ctx context.Context, episodeID int64) ([]ListSegmentsByEpisodeRow, error)
	// Finalize an exhausted stage: record a neutral error_id and flip to 'failed'.
	// Org-scoped and gated on 'processing' for the same reason as MarkEpisodeReady.
	// claimed_at is cleared: the run is done, no claim is in flight.
	MarkEpisodeFailed(ctx context.Context, arg MarkEpisodeFailedParams) (Episode, error)
	// Finalize a successful run: flip to 'ready', preserving the outputs earlier
	// stages recorded. proxy_object_key/duration_ms are COALESCEd (a NULL arg leaves
	// the existing value untouched), so the terminal stage — which today is
	// transcribe, and produces no proxy or duration of its own — does not wipe the
	// proxy key and measured duration ingest recorded. A stage that DOES produce them
	// (a single-stage pipeline where ingest is terminal) still passes non-NULL and
	// sets them, exactly as before. Org-scoped and gated on 'processing' so it only
	// ever completes the run this worker claimed (idempotent no-op otherwise).
	// claimed_at is cleared: the run is done, no claim is in flight.
	MarkEpisodeReady(ctx context.Context, arg MarkEpisodeReadyParams) (Episode, error)
	// State-guarded retry: atomically move a single 'failed' episode back to
	// 'uploaded' so the ingest trigger can re-run it, clearing the prior error_id.
	// Org-scoped and gated on status = 'failed', so a caller can only retry their
	// own org's failed episode and a row in any other state is left untouched
	// (pgx.ErrNoRows, which the handler maps to 409). claimed_at is cleared: the row
	// returns to the unclaimed 'uploaded' state and the next claim stamps it fresh.
	RetryFailedEpisode(ctx context.Context, arg RetryFailedEpisodeParams) (Episode, error)
	// Record the verified master object key after the client confirms the upload
	// landed. Org-scoped so a caller can only complete an upload for their own org's
	// episode. Status is left as 'uploaded'; the worker flips it later.
	SetEpisodeMasterKey(ctx context.Context, arg SetEpisodeMasterKeyParams) (Episode, error)
	// Renumber one moment (by internal id) during the replace choreography. Only
	// ever called inside the ReplaceMoments transaction; rank is otherwise
	// immutable.
	SetMomentRank(ctx context.Context, arg SetMomentRankParams) error
	// Stamp one segment's episode-local diarization label (speaker_key) by
	// (episode_id, idx). The diarize stage calls this for every segment inside one
	// transaction, so a re-run overwrites the prior speaker grouping wholesale
	// (idempotent). episode_id is the internal id, resolved org-scoped by the caller.
	// Only speaker_key changes — text, words, and timings are never touched here
	// (verbatim invariant: the LLM decides grouping, it never rewrites the transcript).
	SetSegmentSpeaker(ctx context.Context, arg SetSegmentSpeakerParams) error
	// Tenant-facing soft delete (CLAUDE.md soft-delete convention): stamp
	// deleted_at once and keep the row. Every read/claim/finalize/sweep path
	// filters deleted_at IS NULL, so a deleted episode is invisible to the API,
	// unclaimable by pipeline stages, and unbillable — deleting a mid-flight
	// episode cleanly starves its stage chain. Org-scoped: a caller can only ever
	// delete their own org's episode; an unknown/foreign id matches no row (the
	// handler's 404). Idempotent: an already-deleted row still matches (COALESCE
	// preserves the original deleted_at and updated_at is only bumped on the first
	// delete), so a repeated DELETE reports the row again (the handler's 204).
	// Storage objects (master/proxy) are deliberately NOT removed here: soft
	// delete is row-level only, and object GC for deleted episodes is a later,
	// separate concern.
	SoftDeleteEpisode(ctx context.Context, arg SoftDeleteEpisodeParams) (int64, error)
	// System-level TTL sweep of abandoned uploads: a create can succeed
	// server-side and then the CLIENT abandons the upload (CORS failure, closed tab,
	// lost network), leaving a row stuck at 'uploaded' with no master key that no
	// future PUT will ever complete. Across ALL orgs (this is a system maintenance
	// sweep, not a tenant action, so it is deliberately not org-scoped) hard-delete
	// rows older than the TTL whose upload never landed. The gate is the same narrow
	// orphan shape as the create-time rollback (status 'uploaded', no master key)
	// plus an age floor, so it can only ever remove a long-abandoned half-created
	// row — never an episode that started uploading or advanced. Returns the count.
	// deleted_at IS NULL: a soft-deleted row is a frozen record of a tenant action
	// (the user removed the episode); the sweep must neither resurrect nor
	// hard-delete it.
	SweepAbandonedEpisodes(ctx context.Context, ttl pgtype.Interval) (int64, error)
	// System-level stale-claim sweep: the backstop for a worker that entered
	// 'processing' (Claim) but was SIGKILLed / OOM-killed / crashed before it could
	// finalize the episode ready or failed. Cloud Run reports such an execution
	// "succeeded" (the retry attempt sees 'processing' and cleanly no-ops), so the
	// row would otherwise sit in 'processing' forever and the retry API — which only
	// accepts 'failed' — could never rescue it. Across ALL orgs (system maintenance,
	// deliberately not org-scoped) force-fail rows stuck in 'processing' whose claim
	// is older than the TTL, OR whose claimed_at is NULL. A NULL claimed_at is a
	// legacy claim taken before the claimed_at column existed (the currently-stuck
	// prod episodes): treated as stale so the sweep unsticks them on the first pass.
	// A neutral error_id is recorded (server-side correlation only, never client
	// surface) and claimed_at cleared. Returns the count so the caller can WARN.
	SweepStuckProcessingEpisodes(ctx context.Context, arg SweepStuckProcessingEpisodesParams) (int64, error)
	// Flip one moment's review status, guarded to the legal transitions only:
	// proposed -> approved/dismissed (the review verdicts) and approved/dismissed ->
	// proposed (the undo). Any other combination matches no row, so the caller sees
	// pgx.ErrNoRows and refuses cleanly. status_changed_at stamps the change.
	// episode_id is the internal id, resolved org-scoped by the caller; (episode_id,
	// rank) is the moment's stable natural key (UNIQUE in the schema).
	TransitionMomentStatus(ctx context.Context, arg TransitionMomentStatusParams) (TransitionMomentStatusRow, error)
	UpdateEpisodeStatus(ctx context.Context, arg UpdateEpisodeStatusParams) (Episode, error)
}

var _ Querier = (*Queries)(nil)
