// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: segments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteEpisodeSegments = `-- name: DeleteEpisodeSegments :exec
DELETE FROM segments WHERE episode_id = $1
`

// Remove all of an episode's segments. Paired with InsertSegment inside one
// transaction, this makes a re-run of the transcribe stage idempotent: the prior
// transcript is replaced wholesale rather than duplicated. episode_id is the
// internal id, resolved org-scoped by the caller.
func (q *Queries) DeleteEpisodeSegments(ctx context.Context, episodeID int64) error {
	_, err := q.db.Exec(ctx, deleteEpisodeSegments, episodeID)
	return err
}

const insertSegment = `-- name: InsertSegment :exec
INSERT INTO segments (episode_id, idx, start_ms, end_ms, text, words)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertSegmentParams struct {
	EpisodeID int64
	Idx       int32
	StartMs   int32
	EndMs     int32
	Text      string
	Words     []byte
}

// Insert one transcript segment. `words` is the positional jsonb array the schema
// documents ([text, start_ms, end_ms, conf] tuples); text/words are stored
// verbatim from ASR (no normalization at rest). speaker_key starts NULL (not yet
// diarized); the diarize stage sets it later via SetSegmentSpeaker.
func (q *Queries) InsertSegment(ctx context.Context, arg InsertSegmentParams) error {
	_, err := q.db.Exec(ctx, insertSegment,
		arg.EpisodeID,
		arg.Idx,
		arg.StartMs,
		arg.EndMs,
		arg.Text,
		arg.Words,
	)
	return err
}

const listSegmentsByEpisode = `-- name: ListSegmentsByEpisode :many
SELECT idx, start_ms, end_ms, text, words, speaker_key
FROM segments
WHERE episode_id = $1
ORDER BY idx
`

type ListSegmentsByEpisodeRow struct {
	Idx        int32
	StartMs    int32
	EndMs      int32
	Text       string
	Words      []byte
	SpeakerKey pgtype.Text
}

// List an episode's transcript in order, including the diarization speaker_key
// (NULL until the diarize stage runs). episode_id is the internal id, resolved
// org-scoped by the caller.
func (q *Queries) ListSegmentsByEpisode(ctx context.Context, episodeID int64) ([]ListSegmentsByEpisodeRow, error) {
	rows, err := q.db.Query(ctx, listSegmentsByEpisode, episodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSegmentsByEpisodeRow{}
	for rows.Next() {
		var i ListSegmentsByEpisodeRow
		if err := rows.Scan(
			&i.Idx,
			&i.StartMs,
			&i.EndMs,
			&i.Text,
			&i.Words,
			&i.SpeakerKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSegmentSpeaker = `-- name: SetSegmentSpeaker :exec
UPDATE segments SET speaker_key = $3 WHERE episode_id = $1 AND idx = $2
`

type SetSegmentSpeakerParams struct {
	EpisodeID  int64
	Idx        int32
	SpeakerKey pgtype.Text
}

// Stamp one segment's episode-local diarization label (speaker_key) by
// (episode_id, idx). The diarize stage calls this for every segment inside one
// transaction, so a re-run overwrites the prior speaker grouping wholesale
// (idempotent). episode_id is the internal id, resolved org-scoped by the caller.
// Only speaker_key changes — text, words, and timings are never touched here
// (verbatim invariant: the LLM decides grouping, it never rewrites the transcript).
func (q *Queries) SetSegmentSpeaker(ctx context.Context, arg SetSegmentSpeakerParams) error {
	_, err := q.db.Exec(ctx, setSegmentSpeaker, arg.EpisodeID, arg.Idx, arg.SpeakerKey)
	return err
}
