// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: segments.sql

package db

import (
	"context"
)

const deleteEpisodeSegments = `-- name: DeleteEpisodeSegments :exec
DELETE FROM segments WHERE episode_id = $1
`

// Remove all of an episode's segments. Paired with InsertSegment inside one
// transaction, this makes a re-run of the transcribe stage idempotent: the prior
// transcript is replaced wholesale rather than duplicated. episode_id is the
// internal id, resolved org-scoped by the caller.
func (q *Queries) DeleteEpisodeSegments(ctx context.Context, episodeID int64) error {
	_, err := q.db.Exec(ctx, deleteEpisodeSegments, episodeID)
	return err
}

const insertSegment = `-- name: InsertSegment :exec
INSERT INTO segments (episode_id, idx, start_ms, end_ms, text, words)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertSegmentParams struct {
	EpisodeID int64
	Idx       int32
	StartMs   int32
	EndMs     int32
	Text      string
	Words     []byte
}

// Insert one transcript segment. `words` is the positional jsonb array the schema
// documents ([text, start_ms, end_ms, conf] tuples); text/words are stored
// verbatim from ASR (no normalization at rest).
func (q *Queries) InsertSegment(ctx context.Context, arg InsertSegmentParams) error {
	_, err := q.db.Exec(ctx, insertSegment,
		arg.EpisodeID,
		arg.Idx,
		arg.StartMs,
		arg.EndMs,
		arg.Text,
		arg.Words,
	)
	return err
}

const listSegmentsByEpisode = `-- name: ListSegmentsByEpisode :many
SELECT idx, start_ms, end_ms, text, words
FROM segments
WHERE episode_id = $1
ORDER BY idx
`

type ListSegmentsByEpisodeRow struct {
	Idx     int32
	StartMs int32
	EndMs   int32
	Text    string
	Words   []byte
}

// List an episode's transcript in order. episode_id is the internal id, resolved
// org-scoped by the caller.
func (q *Queries) ListSegmentsByEpisode(ctx context.Context, episodeID int64) ([]ListSegmentsByEpisodeRow, error) {
	rows, err := q.db.Query(ctx, listSegmentsByEpisode, episodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSegmentsByEpisodeRow{}
	for rows.Next() {
		var i ListSegmentsByEpisodeRow
		if err := rows.Scan(
			&i.Idx,
			&i.StartMs,
			&i.EndMs,
			&i.Text,
			&i.Words,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
