// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shows.sql

package db

import (
	"context"
)

const getDefaultShowForOrg = `-- name: GetDefaultShowForOrg :one
SELECT id, public_id, org_id, title, created_at, updated_at, deleted_at FROM shows
WHERE org_id = $1
  AND deleted_at IS NULL
ORDER BY id
LIMIT 1
`

// The org's canonical show. Setup auto-creates exactly one show per org in M0,
// so the lowest-id non-deleted show is that show. Every episode hangs off it
// until per-show organization arrives.
func (q *Queries) GetDefaultShowForOrg(ctx context.Context, orgID int64) (Show, error) {
	row := q.db.QueryRow(ctx, getDefaultShowForOrg, orgID)
	var i Show
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
