// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stage_runs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const finishStageRun = `-- name: FinishStageRun :execrows
UPDATE stage_runs
SET finished_at = now(),
    outcome     = $1,
    cost_cents  = COALESCE(
        $2,
        CASE WHEN stage_runs.stage IN ('diarize', 'moments') THEN (
            SELECT SUM(l.cost_cents)::int
            FROM llm_calls l
            WHERE l.episode_id = stage_runs.episode_id
              AND l.created_at >= stage_runs.started_at
        ) END
    ),
    items_in  = $3,
    items_out = $4,
    attempt   = $5,
    params    = $6
WHERE stage_runs.id = $7
  AND stage_runs.finished_at IS NULL
`

type FinishStageRunParams struct {
	Outcome   pgtype.Text
	CostCents pgtype.Int4
	ItemsIn   pgtype.Int4
	ItemsOut  pgtype.Int4
	Attempt   pgtype.Int4
	Params    []byte
	ID        int64
}

// Close a stage-run row at finalize time: stamp finished_at, the outcome, and
// whatever the run learned (unit counts, billable attempt, tunables). Gated on
// finished_at IS NULL so a double finalize (e.g. a lost race) is an idempotent
// no-op that never rewrites a closed run.
//
// cost_cents: an explicitly computed cost (the ASR duration-rate) wins; when
// none is passed, an LLM-backed stage (diarize/moments) links the cost from the
// llm_calls audit — the sum of the episode's call costs recorded since this
// run started. SUM over no rows is NULL, so a run with no audited cost stays
// honestly unknown rather than zero.
func (q *Queries) FinishStageRun(ctx context.Context, arg FinishStageRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishStageRun,
		arg.Outcome,
		arg.CostCents,
		arg.ItemsIn,
		arg.ItemsOut,
		arg.Attempt,
		arg.Params,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertStageRun = `-- name: InsertStageRun :one
INSERT INTO stage_runs (episode_id, stage, engine_label, engine_detail)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertStageRunParams struct {
	EpisodeID    int64
	Stage        string
	EngineLabel  pgtype.Text
	EngineDetail pgtype.Text
}

// Open a stage-run provenance row at claim time: append-only history, so a
// re-run/retry INSERTS a new row (never updates the old one) and display reads
// take the latest row per stage. started_at is the DB clock (DEFAULT now()) —
// the wall-clock record; duration is derived at read time, never stored.
// engine_detail is the PRIVATE provider truth and never leaves the server;
// engine_label is the PUBLIC versioned neutral label.
func (q *Queries) InsertStageRun(ctx context.Context, arg InsertStageRunParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertStageRun,
		arg.EpisodeID,
		arg.Stage,
		arg.EngineLabel,
		arg.EngineDetail,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const latestStageRuns = `-- name: LatestStageRuns :many
SELECT DISTINCT ON (stage)
    id, episode_id, stage, started_at, finished_at, outcome,
    engine_label, engine_detail, cost_cents, items_in, items_out, attempt, params
FROM stage_runs
WHERE episode_id = $1
ORDER BY stage, started_at DESC, id DESC
`

// The display read: the LATEST run per stage for one episode (history rows on
// re-runs; latest-per-stage wins). engine_detail is deliberately selected too —
// this query serves the SERVER-side port; the api layer's port type has no
// field for it, so it can never reach a DTO.
func (q *Queries) LatestStageRuns(ctx context.Context, episodeID int64) ([]StageRun, error) {
	rows, err := q.db.Query(ctx, latestStageRuns, episodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StageRun{}
	for rows.Next() {
		var i StageRun
		if err := rows.Scan(
			&i.ID,
			&i.EpisodeID,
			&i.Stage,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Outcome,
			&i.EngineLabel,
			&i.EngineDetail,
			&i.CostCents,
			&i.ItemsIn,
			&i.ItemsOut,
			&i.Attempt,
			&i.Params,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
