// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAuthContextByEmail = `-- name: GetAuthContextByEmail :one
SELECT
    u.email        AS user_email,
    u.display_name AS user_display_name,
    o.public_id    AS org_public_id,
    o.name         AS org_name,
    m.role         AS role
FROM users u
JOIN memberships m ON m.user_id = u.id
JOIN orgs o ON o.id = m.org_id
WHERE u.email = $1
  AND u.deleted_at IS NULL
LIMIT 1
`

type GetAuthContextByEmailRow struct {
	UserEmail       string
	UserDisplayName string
	OrgPublicID     pgtype.UUID
	OrgName         string
	Role            string
}

// Resolve a seeded user's authentication context by email: their display name,
// their org (public id + name) and their role in that org. One membership per
// user in M0, so LIMIT 1 is exact. Soft-deleted users are excluded.
func (q *Queries) GetAuthContextByEmail(ctx context.Context, email string) (GetAuthContextByEmailRow, error) {
	row := q.db.QueryRow(ctx, getAuthContextByEmail, email)
	var i GetAuthContextByEmailRow
	err := row.Scan(
		&i.UserEmail,
		&i.UserDisplayName,
		&i.OrgPublicID,
		&i.OrgName,
		&i.Role,
	)
	return i, err
}
